### ISSUE TITLE
安装依赖后iOS无法运行

### ISSUE THREAD

**Issue by zhenshanxu** [Konoha-orz/flutter_ddshare#3]

**Comment by Konoha-orz** [comment]
Build Settings 中设置Allow Non-modular Includes In Framework Modules 为YES

**Comment by zhenshanxu** [comment]
你好，设置为yes后iOS可以正常运行，真机打包都可以。Android连接真机也可以，但是Android打release包分享提示分享失败，请稍后重试，我的debug和release配置是公用一套签名的， 请问你有遇到过吗？

**Comment by Konoha-orz** [comment]
确保注册的Appid与钉钉开发者平台的Appid要相对应噢

**Comment by zhenshanxu** [comment]
是对应的，因为连接Android真机运行的时候是可以分享出去的，只是打完正式包就不行了，你那边打正式包也可以分享吗？

**Comment by Konoha-orz** [comment]
目前生产环境使用没问题。你的项目是否有用到混淆，如果有的话在proguard.cfg加上下面两行配置试试：
   -keep class com.android.dingtalk.share.ddsharemodule.** {*;}
注意事项可以参考官方文档：https://ding-doc.dingtalk.com/doc#/native/oguxo2

**Comment by Konoha-orz** [comment]
1.0.2版本更新了混淆忽略，你可以升级试试

**Comment by zhenshanxu** [comment]
感谢，有用，继续关注！

**Comment by Konoha-orz** [comment]
Thanks♪(･ω･)ﾉ
